version: '3.8'

services:
  # Requirement for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
  
  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"  # Connecting from out local machine
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1
    restart: always

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

  # Neo4j
  neo4j:
    image: neo4j:5.20.0
    container_name: neo4j
    ports:
      - "7474:7474"  # Browser UI
      - "7687:7687"  # Bolt for python driver
    environment:
      NEO4J_AUTH: neo4j/password123  # Default username and password
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
    volumes:
      - ./neo4j/data:/data  # Persist data
    restart: always

  ollama:
    build:
      context: ./ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: ["gpu"]
    restart: always

  # Consumer
  consumer:
    build:
      context: ./consumer
    container_name: consumer
    env_file:
      - ./.env
    depends_on:
      - kafka
      - redis
    volumes:
      - ./raw_data:/app/raw_data:ro
    restart: always
  
  # Producer
  producer:
    build:
      context: ./producer
    container_name: producer
    env_file:
      - ./.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - kafka
    restart: always
    volumes:
      - ./producer/feeds.json:/app/feeds.json:ro  # Mount feeds config
      - ./producer/processed_articles.log:/app/processed_articles.log  # Mount processed articles log
      - ./raw_data:/app/raw_data

  # curator
  curator:
    build:
      context: ./curator
    container_name: curator
    env_file:
      - ./.env
    depends_on:
      - redis
      - neo4j
      - ollama
    restart: always
  
  # Web app
  webapp:
    build:
      context: ./webapp
    container_name: webapp
    ports:
      - "8501:8501"  # Streamlit default port
    env_file:
      - ./.env
    depends_on:
      - neo4j
      - ollama
    restart: always


volumes:
  redis-data:
  neo4j-data: